### ISSUE TITLE
Getting java.net.unknownHostException

### ISSUE THREAD

**Issue by rdmpage** [bio-guoda/guoda-datasets#12] opened 2018-05-30 20:56 UTC
Working my way through the instructions, when I get to `./installWikidata.sh` Wikidata is downloaded, but then I get `+put java.net.unknownHostException: gouda` I'm a complete newbie to HDFS, but it seems that is the only shell script with `hdfs://` so maybe there's some issue talking to the file system?

<img width="981" alt="screenshot 2018-05-30 21 51 20" src="https://user-images.githubusercontent.com/83306/40746990-df81157e-6453-11e8-98f2-f203e4f9d098.png">

**Comment by mjcollin** [comment] 2018-05-30 21:09
I believe it's supposed to be 
```
hdfs dfs -put latest-all.json.bz2 /guoda/data/source=wikidata/date=20171227/latest.all.json.bz2
```
The hadoop.conf on this host already has connections strings to know where the HDFS nodes are so there's no need for a URL-style reference, a regular file reference refers to the HDFS file system.

If you're reproducing, it is possible you'll get a permission denied since that file already exists in HDFS. If you end up overwriting, that's ok too.

**Comment by rdmpage** [comment] 2018-05-30 21:41
@mjcollin Thanks, that seems to work, except now it's compiling about the lack of `latest-all.json.bz2`. Is it possible that the shell script is missing a step whereby the downloaded Wikidata file is renamed `latest-all.json.bz2` ?

**Comment by mjcollin** [comment] 2018-06-01 14:28
@rdmpage Please pull and re-test and close this issue if it works for you. Thanks for digging in to the code deep enough to find this.

**Comment by jhpoelen** [comment] 2019-01-22 17:48
Closing stale issue.

**Closed as completed by jhpoelen** 2019-01-22 17:48 UTC
